[split-monitor-workspaces]
description = "Split monitor workspaces"
version = "0.1"
author = "MaxCG"

[split-monitor-workspaces.build]
output = "build/libsplit-monitor-workspaces.so"
steps = [
    "meson setup build --wipe",
    "meson compile -C build",
]
